### ISSUE TITLE
Create project sync service

### ISSUE THREAD

**Issue by pontus** [NBISweden/aida-data-hub#875]
We should have something that ensures we have good state in openstack, avoid people doing things manually (which can lead to mistake or things being dependent on who does it).

So I envision a service that gets state from a file (suggested format below) and for all project in there verifies that it exists and that the member list is correct (e.g. if a project is disabled it should have no members, if it's enabled all the listed members should be members in openstack if they exist there, if someone is a member in openstack but not listed, they should be removed in openstack, if the project doesn't exist it should be created with `newtenant`)

Possible format:

```
---

projects:
  - name: project1
    enabled: true
    members:
      - user1@example.com
      - user2@university.invalid
      - user3@somewhere.invalid
  - name: project2
    enabled: true
    members:
      - user2@university.invalid
      - user4@example.com

```
other attributes than the ones included above should not be considered (e.g. if `project2` has an `admins` list, it shouldn't be a consideration here.
